# Generated by Django 4.0.5 on 2022-06-27 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terrenos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terreno',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
