# Generated by Django 4.0.4 on 2023-04-07 04:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0005_terreno_ca_terreno_eficiencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terreno',
            old_name='metragemMall',
            new_name='coef_aprov',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='NumAndarNr',
            new_name='fachada_ativa',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='andarNr',
            new_name='qnt_andares_Garagem',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='andares',
            new_name='tipo_vaga',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='andaresGaragem',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='andaresMall',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='numAndar',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='numMotos',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='quantNr',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='title',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='torre',
        ),
        migrations.AddField(
            model_name='terreno',
            name='operacao_urbana',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='terreno',
            name='qnt_andares_torre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='terreno',
            name='qnt_apartamentos_andar',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='terreno',
            name='qnt_torres_tipo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='terreno',
            name='tipo_torre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='eficiencia',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='garagem',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='gestor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='nomeTerreno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='publico',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='zoneamento',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
