# Generated by Django 4.0.4 on 2023-04-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0016_alter_terreno_qnt_andares_torre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terreno',
            name='qnt_andares_torre',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='qnt_apartamentos_andar',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='qnt_torres_tipo',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='tipo_torre',
        ),
    ]
