# Generated by Django 4.0.4 on 2023-04-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0017_remove_terreno_qnt_andares_torre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terreno',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='fachada_ativa',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='garagem',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='metragem',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='nomeTerreno',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='numVagas',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='operacao_urbana',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='publico',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='qnt_andares_Garagem',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='quantTorre',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='tipo_vaga',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='zoneamento',
        ),
    ]
