# Generated by Django 4.0.4 on 2023-04-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0019_terreno_codigo_terreno_fachada_ativa_terreno_garagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='codigo',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='coef_aprov',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='eficiencia',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='fachada_ativa',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='garagem',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='gestor',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='metragem',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='nomeTerreno',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='numVagas',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='operacao_urbana',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='publico',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='qnt_andares_Garagem',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='quantTorre',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='tipo_vaga',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='zoneamento',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
