# Generated by Django 4.0.4 on 2023-04-09 02:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0022_remove_terreno_qnt_andares_torre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terreno',
            old_name='qnt_andares_Garagem',
            new_name='andares_Garagem',
        ),
        migrations.AddField(
            model_name='terreno',
            name='apartamentos_andar',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='terreno',
            name='qnt_andares_torre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='terreno',
            name='qnt_torres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='terreno',
            name='tipo_torre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='tipo_vaga',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
