# Generated by Django 4.0.4 on 2023-04-10 02:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0025_remove_terreno_quanttorre'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='quantTorre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
