# Generated by Django 4.0.4 on 2023-04-10 02:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0026_terreno_quanttorre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terreno',
            old_name='andaresGaragem',
            new_name='andares_Garagem',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='apartAndar',
            new_name='apartamentos_andar',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='fachadaAtiva',
            new_name='fachada_ativa',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='tipovaga',
            new_name='operacao_urbana',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='quantAndar',
            new_name='qnt_andares_torre',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='tipoTorre',
            new_name='tipo_torre',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='tipoFachadaAtiva',
        ),
        migrations.AddField(
            model_name='terreno',
            name='qnt_torres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='terreno',
            name='tipo_vaga',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='quantTorre',
            field=models.IntegerField(null=True),
        ),
    ]
