# Generated by Django 4.0.4 on 2023-04-10 02:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0027_rename_andaresgaragem_terreno_andares_garagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terreno',
            old_name='andares_Garagem',
            new_name='andaresGaragem',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='apartamentos_andar',
            new_name='apartAndar',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='fachada_ativa',
            new_name='fachadaAtiva',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='qnt_andares_torre',
            new_name='quantAndar',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='tipo_torre',
            new_name='tipoTorre',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='operacao_urbana',
            new_name='tipovaga',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='qnt_torres',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='tipo_vaga',
        ),
        migrations.AddField(
            model_name='terreno',
            name='tipoFachadaAtiva',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='quantTorre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
