# Generated by Django 4.0.4 on 2023-04-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0028_rename_andares_garagem_terreno_andaresgaragem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terreno',
            name='quantTorre',
        ),
    ]
