# Generated by Django 4.0.4 on 2023-04-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0029_remove_terreno_quanttorre'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='quantTorre',
            field=models.IntegerField(null=True),
        ),
    ]
