# Generated by Django 4.0.4 on 2023-04-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0030_terreno_quanttorre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terreno',
            name='quantTorre',
        ),
    ]
